name: gas

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        git config --global user.email "whd1073363531@qq.com"
        git config --global user.name "ParseDark"
        npm i
        cross-env TOKEN=${{ secrets.TOKEN }} npm run deploy 
      env:
        CI: true
        token: ${{ secrets.TOKEN }}
        TOKEN: ${{ secrets.TOKEN }}
