name: gas

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        TOKEN=${{ secrets.TOKEN }}
      env:
        CI: true

    - name: Gatsby Publish
      uses: enriikke/gatsby-gh-pages-action@v2.1.1
      with:
        # A personal access token needed to push your site after it has been built.
        access-token: whd1073363531@qq.com:whd19941127@
        # The branch expected by GitHub to have the static files needed for your site.
        deploy-branch: prod
        gatsby-args: --prefix-paths
